### PR TITLE
Add detach method

### LINKED ISSUE #2: Add detatch to remove packet servers
Add a method `PacketEventAbstract * SimplePacketComsAbstract::detach(uint32_t id)` which accepts a packet id, detatches the packet from the coms device, and returns the detatched packet.

The implementation takes three steps:

1. Get the `PacketEventAbstract*` packet.
2. Detach the packet. (Assuming there is no need to synchronize with `void SimplePacketComsAbstract::server()` since modifying `fmap` would invalidate the iterator inside of that method, but I don't think the API is thread-safe to begin with, so no need to be thread-safe here)
3. Return the packet, passing ownership of the memory back to the caller.

There are two options to implement step 1:

1. Search the `fmap` vector to find the packet. This is literally a *search*, and the `fmap` vector is unordered, so it would take O(n) time.
2. Refactor the implementation so that `fmap` is a `std::map` instead of `std::vector`; then, instead of searching we can index into the map, which takes O(log n) time. This is both faster and easier to implement, but requires an API-breaking change because you expose `fmap` in the method `std::vector<PacketEventAbstract*> * SimplePacketComsAbstract::getfMap()`.

### PR DESCRIPTION
**Pull request by Octogonapus**
This PR closes #2. I'm not sure how to test it, though. How do I build this library, and how can I test it with the esp32 implementation?

### CODE REVIEW

**Comment by Octogonapus** [comment]
@madhephaestus Seriously, you're just going to merge this? I don't even know if it compiles!

**Comment by madhephaestus** [comment]
why would you submit a PR if its not tested...?

**Comment by Octogonapus** [comment]
Did you read my comment? Why would you merge a PR without reading what the author wrote?

**Comment by madhephaestus** [comment]
does your test firmware compile and use this function appropriately?

**Comment by Octogonapus** [comment]
I didn't write any test firmware. As I wrote previously, "I'm not sure how to test it, though. How do I build this library, and how can I test it with the esp32 implementation?". So, is there a test program I don't know about?

**Comment by madhephaestus** [comment]
I test using this FW https://github.com/madhephaestus/ESP32ServoServer and this example https://github.com/madhephaestus/EspWii/tree/master/examples/ControllerServer with a live SmallKat

I tested your changes and it works on both firmwares.

**Comment by Octogonapus** [comment]
Thank you. Can you please tell me how I can test it myself, for future changes?

**Comment by madhephaestus** [comment]
To test on hardware, prepare an esp32 with a BNO055 and some servos. 

check out your copy of SImplePacketComs in the Arduino/libraries directory

install the other libraries from the Library manager : https://github.com/madhephaestus/ESP32ServoServer#depenencies

Compile and burn this FW https://github.com/madhephaestus/ESP32ServoServer

Run https://github.com/OperationSmallKat/greycat.git launch.groovy

run the walking cycle. Observe that the leg positions look like a proper walking cycle, that means downstream and upstream communications are working. Tilt the BNO055 and run the walking again, see that the tail spins to compensate. This tests that both servers are attached on the esp32 and are sending data upstream.

**Pull request merged**
